---
title: "Research Proposal: Effects of income inequality on environment"
author: "Raju Adhikari and Mario Alonso Rodriguez"
date: "October 28, 2016"
output: html_document
bibliography: sources.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## What is the Research Question:

Does income inequality affect the environment?


## Importance of the research question:

Income inequality is one of the biggest issues grappling both developing and developed countries alike. While most development agendas in the past have focused heavily on poverty, it has been clearly established that income inequality is the pressing issue now. The UN Sustainable Development Goals have also put a strong emphasis on income inequality. Increased urbanization and growing reliance on international trade have made the differences between the poor and the rich even more bigger and through globalization it has become more visible to all. Inequality has been looked upon as a cause to many social, political and economic crisis around the world. Plethora of research on inequality show that it affects education, healthcare [@lynch2000income], economy, and even voter turnout and elections in many countries. However, the focus of our research is not going to be in any of these social or political issues. We aim to research the effect of inequality on environment. The reason we find this interesting is because climate change is one of the biggest threats of our generation. Yet it is very much disconnected with other social and economic issues that scholars usually talk about. Showing a relationship between inequality and environment can be extremely important to create a better roadmap for development since policymakers may find better approaches to solve these issues if they are somehow related.

## Literature Review:

A few scholars have already connect the dots and analyzed the relationship between inequality and environment. Nobel Laureate Joseph E. Stiglitz argues that inequality can contribute to environmental degradation because the poor tend to have less interest in pursuing policies designed to protect the environment and therefore good environment policies will be less supported. [@conca2014green] He also argues that the relationship goes both ways in the sense that good environmental policies will help build social cohesion and reduce inequality. [@conca2014green] Roberts believes that global warming is all about inequality based on who created it and who suffers from it the most. [@roberts2001global] Nazrul Islam, a Senior Economic Affairs Officer at the Development Policy Analysis Division of UN DESA provides an analytical framework to explain negative correlations between inequality and quality of environment and suggests that reducing inequality will help protect the environment. (3) He adds that gender inequality is another dimension that affects environment thus providing us even more reason to examine this case. (4) Wilkinson and Pickett argue that equal societies are better in terms of social cohesion and public spiritedness, which they link to being fundamental in responding to environmental issues. [@wilkinson2011spirit] They show statistically that more equal countries recycle a higher proportion of their waste, a clear indication of how inequality affects the environment. [@wilkinson2011spirit]  Sternreview report asserts that climate change is an externality whose cause and consequence both involves deep inequalities. [@stern2007economics] Several other scholars have vigorously analyzed environment and human security [@barnett2007climate], climate change in poor and unequal countries [@gordon2007climate], inequality and resource management [@Baland1999773], inequality and environmental sustainability [@baland2007inequality], and inequality as a cause of environmental degradation [@BOYCE1994169] - all of which provide ample theoretical basis to continue this research.

## Research Methodology and Data Sources:

The methodology for this paper will be divided into two broad sections:

Theoretical analysis: Under this, we will analyze scholarly sources that have influenced the discussion on the relationship between inequality and environment. We will consider various academic sources, reports by international non-governmental organizations and their findings. The United Nations has a ton of resources on this topic yet most are opinion pieces and case studies. Therefore, it gives us the perfect premise to analyze scientific empirical research on the topic. This leads us to our main methodology. 

Statistical analysis: To do a statistical analysis of the issue, it is extremely important to locate data sources. The World Bank Database has all the indicators necessary to do a thorough analysis of the topic. Some of the indicators used to measure inequality are: Gini Index, Palma ratio, etc. We will do a panel data regression with the Gini index as an independent variable and emissions of CO2 per capita as a dependent variable. We could also control for GDP per capita, which shows that the relationship between the two is not determined by the level of income. We will use various descriptive and inferential statistics and use plots, graphs and charts to show various relationship that the model may predict.

## Sources Consulted:
